# Generated by Django 5.1.7 on 2025-06-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='libelle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
