# Generated by Django 5.2.4 on 2025-07-05 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_parking_total_places_alter_place_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='parking',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilisateur'),
        ),
        migrations.CreateModel(
            name='MouvementPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicule')),
            ],
        ),
    ]
